apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ubuntu-demo
  name: ubuntu
  namespace: willdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-demo
  template:
    metadata:
      annotations:
        salad.com/country-codes: us
        salad.com/networking-protocol: "tcp"
        salad.com/networking-port: "22"
        salad.com/networking-auth: "false"
        salad.com/gpu-classes: "dec851b7-eba7-4457-a319-a01b611a810e"
        salad.com/container-group-priority: "high"
      labels:
        app: ubuntu-demo
    spec:
      containers:
        - image: ghcr.io/saladtechnologies/recipe-base-ubuntu:0.1
          name: ubuntu
          resources:
            requests:
              cpu: "1"
              memory: 8Gi
            limits:
              cpu: "1"
              memory: 8Gi
          readinessProbe:
            exec:
              command: [ "cat", "/healthy" ]
            initialDelaySeconds: 3
            failureThreshold: 3
            periodSeconds: 1
            timeoutSeconds: 1
      nodeSelector:
        kubernetes.io/role: agent
        type: virtual-kubelet
      os:
        name: linux
      restartPolicy: Always
      tolerations:
        - key: virtual-kubelet.io/provider
          operator: Equal
          value: saladcloud
          effect: NoSchedule
